---
- name: apt playbook
  hosts: devbox
  sudo: true
  tasks:
  - name: set repositories
    copy: src=files/etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  - name: update repository cache
    apt: cache_valid_time=3600 update_cache=yes
  - name: install packages
    apt: "name={{ item }} state=latest"
    with_items:
      - docker.io
      - git
      - mercurial
      - ctags
      - gnupg2
      - jq
      - keychain
      - mtr
      - netcat
      - nmap
      - ruby-build
      - silversearcher-ag
      - tree
  - name: symlink for docker command
    file: src=/usr/bin/docker.io dest=/usr/bin/docker state=link
  - name: add vagrant user to docker group
    user: append=yes groups=docker name=vagrant
  - name: set readline defaults
    copy: src=files/etc/inputrc dest=/etc/inputrc owner=root mode=0644
  #- name: upgrade distro
  #  apt: upgrade=dist
