---
- name: docker playbook
  hosts: devbox
  sudo: true
  tasks:
  - name: install fig
    shell: "curl -L https://github.com/orchardup/fig/releases/download/0.5.2/linux > /usr/local/bin/fig"
    args:
      creates: /usr/local/bin/fig
  - name: chmod fig
    file: path=/usr/local/bin/fig mode=0755


