---
- name: install dotfiles
  hosts: devbox
  tasks:
    - name: clone dotfiles
      git: repo=git://github.com/JimGaylard/dotfiles.git dest=dotfiles
    - name: clone vundle for vim
      git: repo=git://github.com/gmarik/Vundle.vim.git dest=.vim/bundle/vundle
    - name: install dotfiles
      command: ./makesymlinks.sh
      args:
        chdir: dotfiles
        creates: ~/.vimrc.bundles
    - name: copy tmp vimrc to install plugins
      copy: src=files/tmp/.tmpvimrc dest=/tmp/.tmpvimrc
    - name: install vim plugins
      command: creates=.vim/bundle/nerdtree/README.markdown /usr/bin/vim -u /tmp/.tmpvimrc +PluginInstall! +qall
    - name: link to workspace
      file: src=/host_home/workspace dest=workspace state=link
    - name: link to Dropbox
      file: src=/host_home/Dropbox dest=dropbox state=link force=yes
