---
- name: install dotfiles
  hosts: dev
  tasks:
    - name: clone dotfiles
      git: repo=ssh://git@github.com/JimGaylard/dotfiles.git dest=dotfiles accept_hostkey=yes
    - name: install dotfiles
      command: ./makesymlinks.sh
      args:
        chdir: dotfiles
        creates: ~/.vimrc.bundles
    - name: link to workspace
      file: src=/host_home/workspace dest=workspace state=link
    - name: link to Dropbox
      file: src=/host_home/Dropbox dest=dropbox state=link force=yes
    - name: add bash_local skeleton
      copy: src=files/bash_local dest=.bash_local force=no
    - name: clone bash-my-aws
      git: repo=ssh://git@github.com/realestate-com-au/bash-my-aws.git dest=.bash-my-aws accept_hostkey=yes
