---
- name: install dotfiles
  hosts: devbox
  tasks:
    - name: clone dotfiles
      git: repo=git://github.com/JimGaylard/dotfiles.git dest=dotfiles
    - name: clone vundle for vim
      git: repo=git://github.com/gmarik/Vundle.vim.git dest=.vim/bundle/vundle
    - name: install dotfiles
      command: chdir=dotfiles creates='.vimrc.bundles' ./makesymlinks.sh
    - name: install vim plugins
      # this is not currently working
      command: creates=.vim/bundle/nerdtree/README.markdown /usr/bin/vim +PluginInstall +qall
    - name: link to workspace
      file: src=/host_home/workspace dest=workspace state=link
    - name: link to Downloads
      file: src=/host_home/Downloads dest=downloads state=link
    - name: link to Dropbox
      file: src=/host_home/Dropbox dest=dropbox state=link
