---
- name: packages playbook
  hosts: devbox
  sudo: true
  tasks:
  - name: set repositories
    copy: src=files/etc/apt/sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644
  - name: Add Docker key
    apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=36A1D7869245C8950F966E92D8576A8BA88D21E9
  - name: setup docker repository
    copy: src=files/etc/apt/sources.list.d/docker.list dest=/etc/apt/sources.list.d/docker.list owner=root group=root mode=0644
  - name: add git repository
    apt_repository: repo='ppa:git-core/ppa'
  - name: add neovim repository
    apt_repository: repo='ppa:neovim-ppa/unstable'
  - name: update repository cache
    apt: cache_valid_time=3600 update_cache=yes
  - name: install packages
    apt: "name={{ item }} state=latest"
    with_items:
      - ansible
      - automake
      - cmake
      - ctags
      - git
      - gnupg2
      - haskell-platform
      - jq
      - keychain
      - libmysqlclient-dev
      - libtool
      - libtool
      - lxc-docker
      - mercurial
      - mtr
      - neovim
      - netcat
      - nmap
      - ntp
      - python-dev
      - python-pip
      - silversearcher-ag
      - sipcalc
      - socat
      - software-properties-common
      - tree
      - virtualbox-guest-dkms
      - virtualbox-guest-utils
  - name: install awscli
    pip: name=awscli state=latest
  - name: add vagrant user to docker group
    user: append=yes groups=docker name=vagrant
  - name: set readline defaults
    copy: src=files/etc/inputrc dest=/etc/inputrc owner=root mode=0644
  - name: upgrade distro
    apt: upgrade=dist
  - name: install kernel support for aufs
    apt: "name=linux-image-extra-{{ ansible_kernel }} state=latest"
