---
- name: user playbook
  hosts: devbox
  sudo: true
  vars:
    - home: "{{ lookup('env', 'HOME') }}"
    - hostname: "{{ inventory_hostname }}"
  tasks:
    - name: create my user
      user: "name=jimg comment='Jim Gaylard' generate_ssh_key=yes ssh_key_comment='Vagrant devbox for {{ hostname }}'"
    - name: copy public key to authorized_keys file
      copy: "src='{{ home }}/.ssh/id_rsa.pub' dest=/home/jimg/.ssh/authorized_keys owner=jimg mode=0644 group=admin"

