---
- name: install latest vim
  sudo: true
  hosts: devbox
  tasks:
  - name: clone vim source
    hg: dest=/usr/local/src/vim repo='https://vim.googlecode.com/hg/'
  - name: configure vim
    command: ./configure --with-features=huge
    args:
      chdir: /usr/local/src/vim
      creates: /usr/local/src/vim/src/auto/config.status
  - name: make vim
    command: /usr/bin/make
    args:
      chdir: /usr/local/src/vim
      creates: /usr/local/src/vim/src/vim
  - name: install vim
    command: /usr/bin/make install
    args:
      chdir: /usr/local/src/vim
      creates: /usr/local/bin/vim
