- name: install vim plugins
  hosts: dev
  tasks:
    - name: clone neobundle for vim
      git: repo=git://github.com/Shougo/neobundle.vim.git dest=.config/nvim/bundle/neobundle.vim
    - name: install vim plugins
      command: creates=.config/nvim/bundle/unite.vim/README.md chdir=.config/nvim/bundle/neobundle.vim bin/neoinstall
